WareHouseManagement/Controllers/ProductController.cs
using BusinesLayer.Concrete;
using DataAccessLayer.EntityFrameWork;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using WareHouseManagement.Models;
using System;
using Microsoft.Extensions.Hosting;

namespace WareHouseManagement.Controllers
{
    [Authorize(Roles = "Admin,WareHouse")]
    public class ProductController : Controller
    {
        private IWebHostEnvironment _hostEnvironment;

        ProductManager pmangr = new ProductManager(new EfProductRepository());  
        ProductBrandManager pbrandma = new ProductBrandManager(new EfProductBrandRepository());  
        ProductCategoryManager pcategoryma = new ProductCategoryManager(new EfProductCategoryRepository());  
        WareHouseManager pwarema = new WareHouseManager(new EfWareHouseRepository());
        public ProductController( IWebHostEnvironment environment)
        {
            _hostEnvironment = environment;
        }
        public IActionResult Products(int id)
        {
            ViewData["WareHouseId"] = id;
            return View();
        }

        [HttpGet]
        public object Get(DataSourceLoadOptions loadOptions,int id)
        {
            var a = 0;
            a = id;
            if (a ==0)
            {
                var values = pmangr.GetAllProduct();
                return DataSourceLoader.Load(values, loadOptions);
                
            }
            else if(a !=0)
            {
                var values = pmangr.GetAllProductByWareHouseId(a);
                a = 0;
                return DataSourceLoader.Load(values, loadOptions);
            }
            else
            {
                return Ok();
            }


        }
        [HttpGet]
        public object GetBrand(DataSourceLoadOptions loadOptions)
        {
            var values = pbrandma.GetAllProductBrand();
            return DataSourceLoader.Load(values, loadOptions);
        }        
        [HttpGet]
        public object GetCategory(DataSourceLoadOptions loadOptions)
        {
            var values = pcategoryma.GetAllProductCategory();
            return DataSourceLoader.Load(values, loadOptions);
        }        
        [HttpGet]
        public object GetWareHouse(DataSourceLoadOptions loadOptions)
        {
            var values = pwarema.GetAllWareHouse();
            return DataSourceLoader.Load(values, loadOptions);
        }
        [HttpPost]
        public IActionResult Post(string values)
        {
            var product = new Product();
            JsonConvert.PopulateObject(values, product);
            var warehousee= pwarema.GetWareHouseById(product.Id);
            warehousee.CurrentCapacity = warehousee.CurrentCapacity - product.ProductQuantity;
            warehousee.UsedCapacity = product.ProductQuantity;
            pwarema.UpdateWareHouse(warehousee);
            //if (!TryValidateModel(product))
            //    return Error();
            pmangr.AddProduct(product);
            return Ok();
        }
        [HttpPut]
        public IActionResult Put(int key, string values)
        {
            var product = pmangr.GetProductById(key);
            int oldQuantity = product.ProductQuantity;
            var warehousee = pwarema.GetWareHouseById(product.Id);
            JsonConvert.PopulateObject(values, product);
            pmangr.UpdateProduct(product);
            int newQuantity= product.ProductQuantity;   
            if (oldQuantity != newQuantity)
            {
                var increse = newQuantity - oldQuantity;
                warehousee.CurrentCapacity -= increse;
                warehousee.UsedCapacity += increse;
                pwarema.UpdateWareHouse(warehousee);
            }
            return Ok();
        }
        [HttpDelete]
        public void Delete(int key)
        {
            var product = pmangr.GetProductById(key);
            var warehousee = pwarema.GetWareHouseById(product.Id);
            if (warehousee.UsedCapacity!=0)
            {
                warehousee.CurrentCapacity = warehousee.CurrentCapacity + product.ProductQuantity;
                warehousee.UsedCapacity = warehousee.UsedCapacity - product.ProductQuantity;
                pwarema.UpdateWareHouse(warehousee);
            }

            pmangr.DeleteProduct(product);
        }
        [HttpPost]
        public IActionResult PostPhoto3()
        {
            IFormFileCollection files = Request.Form.Files;
            string uniqueFileName = "";

            if (files.Count > 0)
            {
                var file = files[0];
                uniqueFileName = string.Format("{0}{1}", Guid.NewGuid(), Path.GetExtension(file.FileName));

                try
                {
                    var path = Path.Combine(_hostEnvironment.WebRootPath, "ProductImages/" + uniqueFileName);

                    using (Stream fileStream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                }
                catch
                {
                    return BadRequest("Failed to save a file on the server");
                }
            }

            return Ok(uniqueFileName);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WareHouseManagement/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.AspNetCore.Authorization;
using EntityLayer.Concrete;
using System.Security.Claims;
using DataAccessLayer.EntityFrameWork;
using BusinesLayer.Concrete;
using System.Diagnostics;
using WareHouseManagement.Models;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Newtonsoft.Json;

namespace WareHouseManagement.Controllers
{
    [Authorize(Roles = "Admin,SaleMan")]
    public class SalesController : Controller
    {
        UserManager bm = new UserManager(new EfUserRepository());
        CostumerManager cmm= new CostumerManager(new EfCostumerRepository());
        public IActionResult Index()
        {
            string userıd = null;
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            userıd = userIdClaim.Value;
            var values = bm.GetuserById(Convert.ToInt32(userıd));
            return View(values);
        }
        [HttpGet]
        public object Get(DataSourceLoadOptions loadOptions)
        {
            string userıd = null;
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            userıd = userIdClaim.Value;
            var values = cmm.GetAllCostumerByuserId(Convert.ToInt32(userıd));
            return DataSourceLoader.Load(values, loadOptions);
        }
        [HttpPost]
        public IActionResult Post(string values)
        {
            var newcostumer = new Costumer();
            string userıd = null;
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            userıd = userIdClaim.Value;
            JsonConvert.PopulateObject(values, newcostumer);

            if (!TryValidateModel(newcostumer))
                return Error();
            cmm.AddCostumerwithUserId(newcostumer,Convert.ToInt32(userıd));
            return Ok();
        }
        [HttpPut]
        public IActionResult Put(int key, string values)
        {
            var newcostumer = cmm.GetCostumerById(key);
            JsonConvert.PopulateObject(values, newcostumer);

            if (!TryValidateModel(newcostumer))
                return Error();
            cmm.UpdateCostumerCategory(newcostumer);
            return Ok();
        }
        [HttpDelete]
        public void Delete(int key)
        {
            var newcostumer = cmm.GetCostumerById(key);
            cmm.DeleteCostumerCategory(newcostumer);
        }
        public IActionResult Depo()
        {
            return RedirectToAction("WareHouse", "WareHouse");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

WareHouseManagement/Views/Shared/PartialHeader.cshtml
<header id="header" class="header">
    <div class="top-left">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"><img src="~/elaadmin-master/images/sales-enquiries-wide.png" alt="Logo"></a>
            <a class="navbar-brand hidden" href="#"><img src="~/elaadmin-master/images/sales-enquiries-wide.png" alt="Logo"></a>
            <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
    </div>
    <div class="top-right">
        <div class="header-menu">
            <div class="header-left">
                <button class="search-trigger"><i class="fa fa-search"></i></button>
                <div class="form-inline">
                    <form class="search-form">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                    </form>
                </div>

                <div class="dropdown for-notification">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="count bg-danger">3</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="notification">
                        <p class="red">You have 3 Notification</p>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-check"></i>
                            <p>Server #1 overloaded.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-info"></i>
                            <p>Server #2 overloaded.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-warning"></i>
                            <p>Server #3 overloaded.</p>
                        </a>
                    </div>
                </div>

                <div class="dropdown for-message">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-envelope"></i>
                        <span class="count bg-primary">4</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="message">
                        <p class="red">You have 4 Mails</p>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="images/avatar/1.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Jonathan Smith</span>
                                <span class="time float-right">Just now</span>
                                <p>Hello, this is an example msg</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="images/avatar/2.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Jack Sanders</span>
                                <span class="time float-right">5 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="images/avatar/3.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Cheryl Wheeler</span>
                                <span class="time float-right">10 minutes ago</span>
                                <p>Hello, this is an example msg</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="images/avatar/4.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Rachel Santos</span>
                                <span class="time float-right">15 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div><img src="" />

            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="~/elaadmin-master/images/admin.jpg" alt="User Avatar">
                </a>

                <div class="user-menu dropdown-menu">
                    <a class="nav-link" asp-action="Index" asp-controller="Home"><i class="fa fa- user"></i>Depo</a>

                    <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                    <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                    <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a>
                </div>
            </div>

        </div>
    </div>
</header>

WareHouseManagement/Views/Shared/_CellTemplate.cshtml
@{
    Layout = null;
    string backendUploadURL = "http://localhost:5000/";
}

[%
    editCellInfo = arguments[0]; // get all properties of editCellTemplate
%]

<script>
    function onRetryButtonClick(e) {
        const fileUploader = $("#fileUploader").dxFileUploader("instance");
        for (let i = 0; i < fileUploader._files.length; i++) {
            delete fileUploader._files[i].uploadStarted;
        }
        fileUploader.upload();
    }

    function onFileUploaderValueChanged(e) {
        let reader = new FileReader();
        let imageElement = $("#imgElement1")[0];
        reader.onload = function (args) {
            imageElement.setAttribute('src', args.target.result);
        }
        reader.readAsDataURL(e.value[0]); // convert to base64 string
    }

    function onUploaded(e) {
        let retryButton = $("#retryButton").dxButton("instance");
        editCellInfo.setValue("ProductImages/" + e.request.responseText);
        retryButton.option("visible", false);
    }

    function onUploadError(e) {
        let retryButton = $("#retryButton").dxButton("instance");
        let xhttp = e.request;
        if (xhttp.status === 400) {
            e.message = e.error.responseText;
        }
        if (xhttp.readyState == 4 && xhttp.status == 0) {
            e.message = "Connection refused";
        }
        retryButton.option("visible", true);
    }
</script>

@(Html.DevExtreme().FileUploader()
        .ID("fileUploader")
        .Multiple(false)
        .Accept("image/*")
        .UploadMode(FileUploadMode.Instantly)
        .UploadUrl("PostPhoto3")
        .OnValueChanged("function(e){onFileUploaderValueChanged(e)}")
        .OnUploaded("function(e){onUploaded(e)}")
        .OnUploadError("function(e){onUploadError(e)}")
)

<img id="imgElement1" class="uploadedImage" src="<%- value %>" alt="Photo" />

@(Html.DevExtreme().Button()
        .ID("retryButton1")
        .Text("Retry")
        .Visible(false)
        .Type(ButtonType.Normal)
        .OnClick("function(e){onRetryButtonClick(e)}")
)



WareHouseManagement/Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>WareHouseManagement</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://unpkg.com/devextreme-quill@22_2/dist/dx-quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">WareHouseManagement</a>

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a href="#" class="nav-link active">Home</a></li>
                    <li class="nav-item"><a href="#about" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="#contact" class="nav-link">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container">
        @RenderBody()
    </main>
</body>

</html>

WareHouseManagement/Views/Shared/_EditCellTemplate.cshtml
@{ Layout = null;
    string backendUploadURL = "http://localhost:5000/"; }

[%
    editCellInfo = arguments[0]; // get all properties of editCellTemplate
%]

<script>
    function onRetryButtonClick(e) {
        const fileUploader = $("#fileUploader").dxFileUploader("instance");
        for (let i = 0; i < fileUploader._files.length; i++) {
            delete fileUploader._files[i].uploadStarted;
        }
        fileUploader.upload();
    }

    function onFileUploaderValueChanged(e) {
        let reader = new FileReader();
        let imageElement = $("#imgElement")[0];
        reader.onload = function (args) {
            imageElement.setAttribute('src', args.target.result);
        }
        reader.readAsDataURL(e.value[0]); // convert to base64 string
    }

    function onUploaded(e) {
        let retryButton = $("#retryButton").dxButton("instance");
        editCellInfo.setValue("ImageFiles/" + e.request.responseText);
        retryButton.option("visible", false);
    }

    function onUploadError(e) {
        let retryButton = $("#retryButton").dxButton("instance");
        let xhttp = e.request;
        if (xhttp.status === 400) {
            e.message = e.error.responseText;
        }
        if (xhttp.readyState == 4 && xhttp.status == 0) {
            e.message = "Connection refused";
        }
        retryButton.option("visible", true);
    }
</script>

@(Html.DevExtreme().FileUploader()
        .ID("fileUploader")
        .Multiple(false)
        .Accept("image/*")
        .UploadMode(FileUploadMode.Instantly)
        .UploadUrl("Home/PostPhoto")
        .OnValueChanged("function(e){onFileUploaderValueChanged(e)}")
        .OnUploaded("function(e){onUploaded(e)}")
        .OnUploadError("function(e){onUploadError(e)}")
)

<img id="imgElement" class="uploadedImage" src="<%- value %>" alt="Photo" />

@(Html.DevExtreme().Button()
        .ID("retryButton")
        .Text("Retry")
        .Visible(false)
        .Type(ButtonType.Normal)
        .OnClick("function(e){onRetryButtonClick(e)}")
)

WareHouseManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WareHouseManagement</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WareHouseManagement.styles.css" asp-append-version="true" />*@
    <link href="~/warehouse.png" rel="shortcut icon" type="image/x-icon" />
    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />
    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>
    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <link rel="icon" type="image/png" href="~/warehouse.png">
    <link rel="stylesheet" href="~/css/thirdparty.bundle.css" />
    <script src="~/js/thirdparty.bundle.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WareHouseManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WareHouse" asp-action="WareHouse">Depolar</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WareHouse" asp-action="ProdcutSpecications">Ürün Özellikleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Products">Ürünler</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Satış Bölümü</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Oturumu Kapat</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WareHouseManagement - <a href="#">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WareHouseManagement/Views/Shared/_Login.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="Responsive-Login-Form-master/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <link href="~/css/stylesheet.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script type="text/javascript" src="Responsive-Login-Form-master/js/main.js"></script>
</body>
</html>

WareHouseManagement/Views/Shared/_Sales.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />
    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>
    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <link href="~/css/salesdashboard.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="~/warehouse.png">

    
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="#" asp-action="#">Satış Bölümüne Hoşgeldiniz</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WareHouse" asp-action="WareHouse">Depo Yönetimi</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

</body>
</html>